#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Check if metadata.json is included in the commit
# Probably if we changed something we need to up the version in metadata.json
VER_UPDATED=false

while read line ; do
  if [ "$line" == "metadata.json" ]; then
    VER_UPDATED=true
  fi
done <<< "$(git diff --cached --name-only)"

if [ "$VER_UPDATED" = false ]; then
  echo "Metadata.json file hasn't been updated."
  echo "You probably want to up the version number, right?"
  exit 1
fi

bundle exec rake puppet:lint
bundle exec rake spec

exit $?
