tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
cask 'osxfuse'
brew 'boost'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'docker', args: ['overwrite']
brew 'openssl'
brew 'git-fixup'
brew 'hub'
brew 'pinentry-mac'
brew 'vim', args: ['with-override-system-vi']
brew 'node', args: ['without-npm'] 
brew 'zsh'
brew 'zsh-completions'
brew 'grep'
brew 'openssh'
brew 'encfs'
brew 'tree'
brew 'hugo'
brew 'shellcheck'
brew 'heroku'
brew 'mas'
brew 'python@2'
brew 'bitrise'
brew 'stow'
brew 'bat'
brew 'neovim'
# Prerequisites
brew 'openssl@1.1'
brew 'libpng'
brew 'jpeg'
brew 'freetype'
brew 'gettext'
brew 'pcre'
brew 'readline'
brew 'icu4c'
brew 'libxml2'
brew 'unixodbc'
brew 'sqlite'
brew 'gdbm'
brew 'libyaml'
brew 'gmp'
brew 'openssl'
# End of prerequisites
brew 'composer'
brew 'php@7.1'
brew 'scrcpy'
brew 'yarn'
cask 'android-studio'
cask 'alfred'
cask 'bitwarden'
cask 'evernote'
cask 'google-chrome'
cask 'paw'
cask 'phpstorm'
cask 'spectacle'
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'
cask 'datagrip'
cask 'vlc'
cask 'visual-studio-code'
cask 'rambox'
cask 'gpg-suite'
cask 'insomnia'
cask 'nvalt'
cask 'google-backup-and-sync'
cask 'stack'
cask 'the-unarchiver'
mas "Xcode", id: 497799835
mas "Helium", id: 1054607607
mas "Next Meeting", id: 1017470484
